# Generated by Django 6.0.1 on 2026-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('userRole', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin / Chairman'), ('MEMBER', 'Society Member'), ('SECURITY', 'Security Person'), ('HELPER', 'House Helper')], max_length=15)),
                ('flatNo', models.CharField(max_length=10)),
                ('contactNo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
