# Generated by Django 6.0.1 on 2026-02-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorName', models.CharField(max_length=30)),
                ('visitorType', models.CharField(choices=[('GUEST', 'Guest'), ('SERVICE', 'Service Provider')], max_length=15)),
                ('priorPermission', models.BooleanField()),
                ('approvalStatus', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.user')),
            ],
            options={
                'db_table': 'visitor',
            },
        ),
    ]
