# Generated by Django 6.0.1 on 2026-02-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageLimit', models.IntegerField()),
            ],
            options={
                'db_table': 'child_age_limit',
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.CharField(max_length=30)),
                ('staffRole', models.CharField(choices=[('SECURITY', 'Security'), ('HELPER', 'House Helper')], max_length=20)),
                ('attendanceDate', models.DateField()),
                ('staffInTime', models.TimeField()),
                ('staffOutTime', models.TimeField()),
            ],
            options={
                'db_table': 'staff_attendance',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childName', models.CharField(max_length=30)),
                ('childAge', models.IntegerField()),
                ('inTime', models.TimeField()),
                ('outTime', models.TimeField()),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.user')),
            ],
            options={
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryPerson', models.CharField(max_length=30)),
                ('deliveryAllowed', models.BooleanField()),
                ('deliveryStatus', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected')], max_length=10)),
                ('storedAtSecurity', models.BooleanField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.user')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
    ]
