# Generated by Django 6.0.1 on 2026-02-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_childagelimit_staffattendance_child_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedTime', models.DateTimeField()),
                ('collectedTime', models.DateTimeField(blank=True, null=True)),
                ('deliveryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.delivery')),
            ],
            options={
                'db_table': 'delivery_log',
            },
        ),
        migrations.CreateModel(
            name='SocietyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(max_length=100)),
                ('noticeDescription', models.TextField()),
                ('postedDate', models.DateField()),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.user')),
            ],
            options={
                'db_table': 'society_notice',
            },
        ),
        migrations.CreateModel(
            name='VisitorEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTime', models.DateTimeField()),
                ('exitTime', models.DateTimeField(blank=True, null=True)),
                ('visitorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.visitor')),
            ],
            options={
                'db_table': 'visitor_entry_log',
            },
        ),
    ]
