# Generated by Django 6.0.1 on 2026-02-21 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_deliverylog_societynotice_visitorentrylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryAllowed', models.BooleanField(default=True)),
                ('visitorAllowed', models.BooleanField(default=True)),
                ('defaultAgeLimit', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'society_settings',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='childPhoto',
            field=models.FileField(blank=True, null=True, upload_to='child_photos/'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 21, 11, 9, 44, 523072, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitPurpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='approvalStatus',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='priorPermission',
            field=models.BooleanField(default=False),
        ),
    ]
